# Generated by Django 6.0.2 on 2026-02-09 12:52

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_proof',
            field=models.ImageField(blank=True, help_text='Upload proof of SUST enrollment. Supported formats: JPG, JPEG, PNG. Max size: 5 MB.', null=True, upload_to='student_proofs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), users.models.validate_file_size]),
        ),
    ]
