# Generated by Django 6.0.2 on 2026-02-09 13:01

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_email_verified_customuser_student_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarysetting',
            name='admin_profile',
        ),
        migrations.RemoveField(
            model_name='primarysetting',
            name='registration_open',
        ),
        migrations.AddField(
            model_name='primarysetting',
            name='auto_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='student_proof',
            field=models.ImageField(blank=True, null=True, upload_to='student_proofs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), users.models.validate_file_size]),
        ),
    ]
