# Generated by Django 6.0.2 on 2026-04-26 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_school_customuser_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='short_name',
        ),
    ]
