# Generated by Django 6.0.2 on 2026-04-26 03:30

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_department_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('hashed_password', models.CharField(max_length=128)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('blood', models.CharField(blank=True, max_length=3, null=True)),
                ('hometown', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('social_profile', models.URLField(blank=True, null=True)),
                ('student_proof', models.ImageField(blank=True, null=True, upload_to='pending_proofs/')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.school')),
            ],
        ),
    ]
