# Generated by Django 6.0.2 on 2026-04-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_pendingregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='school',
        ),
    ]
