# Generated by Django 6.0.2 on 2026-04-26 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('pub_type', models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book_chapter', 'Book Chapter'), ('preprint', 'Preprint'), ('technical', 'Technical Report'), ('other', 'Other')], default='journal', max_length=20)),
                ('external_authors', models.TextField(blank=True, help_text='Comma-separated names of co-authors not on the platform.')),
                ('journal_name', models.CharField(blank=True, help_text='Journal or conference name', max_length=300)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, help_text='e.g. 10.1000/xyz123', max_length=200)),
                ('link', models.URLField(blank=True, help_text='External URL (journal site, arXiv, etc.)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-uploaded_at'],
            },
        ),
    ]
