# Generated by Django 6.0.2 on 2026-02-13 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('supervisor_name', models.TextField()),
                ('work_type', models.CharField(choices=[('HONOURS_THESIS', 'Honours Thesis'), ('HONOURS_PROJECT', 'Honours Project'), ('MASTERS_THESIS', 'Masters Thesis'), ('MASTERS_PROJECT', 'Masters Project'), ('PhD_THESIS', 'PhD Thesis'), ('PhD_PROJECT', 'PhD Project')], max_length=20)),
                ('link', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('authors', models.ManyToManyField(related_name='authored_works', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='thesis.researchwork')),
            ],
        ),
    ]
