# Generated by Django 6.0.2 on 2026-04-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_researchwork_embargo_until_thesisaccesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchwork',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
