# Generated by Django 6.0.2 on 2026-04-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0003_add_view_count_to_researchwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchwork',
            name='view_count',
        ),
    ]
